In [1]:
from google.colab import drive
drive.mount('/content/drive')

rawdata_path = '/content/drive/MyDrive/my_project/my_project1/rawdata'
data_path = '/content/drive/MyDrive/my_project/my_project1/data'
final_result = '/content/drive/MyDrive/my_project/my_project1/result/data'
final_img = '/content/drive/MyDrive/my_project/my_project1/result/img'
# rawdata_path = 'rawdata/'
# data_path = 'data/'

Mounted at /content/drive

In [ ]:
year_list = ['2022', '2023', '2024']

for year in year_list:
    globals()[f'temp_{year}'] = pd.read_csv(f'{data_path}/final/final_{year}.csv')

    globals()[f'temp_{year}'][f'solo_20s_{year}'] = globals()[f'temp_{year}'].apply(lambda x: (x[f'solo_20_{year}'] + x[f'solo_25_{year}']) / 2, axis = 1)
    globals()[f'temp_{year}'][f'solo_all_ratio'] = globals()[f'temp_{year}'].apply(lambda x: x[f'solo_all_{year}'] / x[f'total_all_{year}'] * 100, axis=1)
    globals()[f'temp_{year}'][f'solo_20s_ratio'] = globals()[f'temp_{year}'].apply(lambda x: x[f'solo_20s_{year}'] / x[f'solo_all_{year}'] * 100, axis=1)

In [ ]:
reg_col = ['ADM_CD', 'solo_all_ratio', 'solo_20s_ratio',
           '네일숍', '미용실', '애완동물',
           '분식전문점', '한식음식점', '양식음식점', '일식음식점', '중식음식점', '치킨전문점',
           '커피-음료', '패스트푸드점', '제과점', '호프-간이주점',
           '유통업체수', '대형마트', '쇼핑업체수', '편의점', '슈퍼마켓',
           '지가변동률', '지가',
           '사업체수', '종사자수', '금융기관',
           '대학교', '기타대학', '면적', '월평균소득',
           '총상주인구', '20대상주인구', '총직장인구', '20대직장인구']

In [ ]:
df_2022 = temp_2022.copy()
df_2022.head()

In [ ]:
columns_2022 = [col.replace('_2022', '') for col in df_2022.columns]
columns_2023 = [col.replace('_2023', '') for col in columns_2022]
columns_2024 = [col.replace('_2024', '') for col in columns_2023]
df_2022.columns = columns_2024
df_2022.columns

In [ ]:
reg_2022 = df_2022[reg_col]
reg_2022

In [ ]:
df_2023 = temp_2023.copy()
df_2023.head()

In [ ]:
columns_2022 = [col.replace('_2022', '') for col in df_2023.columns]
columns_2023 = [col.replace('_2023', '') for col in columns_2022]
columns_2024 = [col.replace('_2024', '') for col in columns_2023]
df_2023.columns = columns_2024
df_2023.columns

In [ ]:
reg_2023 = df_2023[reg_col]
reg_2023

In [ ]:
df_2024 = temp_2024.copy()
df_2024.head()

In [ ]:
columns_2022 = [col.replace('_2022', '') for col in df_2024.columns]
columns_2023 = [col.replace('_2023', '') for col in columns_2022]
columns_2024 = [col.replace('_2024', '') for col in columns_2023]
df_2024.columns = columns_2024
df_2024.columns

In [ ]:
reg_2024 = df_2024[reg_col]
reg_2024